# Generated by Django 4.0.2 on 2022-04-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_file',
            field=models.FileField(default='https://s3.us-west-2.amazonaws.comcreative-marketplace/ece395.jpeg', max_length=300, upload_to=None),
            preserve_default=False,
        ),
    ]
