# Generated by Django 4.0.2 on 2022-04-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_file',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
