# Generated by Django 4.0.2 on 2022-04-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_product_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_file',
            field=models.ImageField(max_length=300, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
