# Generated by Django 4.0.2 on 2022-04-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_tag_remove_product_likes_like_comment_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
    ]
